// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb63CN8LejpxT18c27kVsZw_2VUfPVLH0',
    appId: '1:387317917599:web:14406f9d9c621e9c70ffaa',
    messagingSenderId: '387317917599',
    projectId: 'mamameow-ca942',
    authDomain: 'mamameow-ca942.firebaseapp.com',
    databaseURL: 'https://mamameow-ca942-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mamameow-ca942.firebasestorage.app',
    measurementId: 'G-8C6Z88T112',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmCcbja7q1NfrgwACqMVdDL-ok8ZuGF0',
    appId: '1:387317917599:android:5872ffcacb69379e70ffaa',
    messagingSenderId: '387317917599',
    projectId: 'mamameow-ca942',
    databaseURL: 'https://mamameow-ca942-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mamameow-ca942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr007SSTju3lMKIlc82tj6rCDYNsT8eRo',
    appId: '1:387317917599:ios:32e6ffe1df2600aa70ffaa',
    messagingSenderId: '387317917599',
    projectId: 'mamameow-ca942',
    databaseURL: 'https://mamameow-ca942-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mamameow-ca942.firebasestorage.app',
    iosBundleId: 'com.yildiz.mamaMeow',
  );

}